services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DEBUG=backend_carevault:*
      - PORT=3001
      - NODE_PATH=/usr/src/shared
    volumes:
      - ./server:/usr/src/app
      - ./shared:/usr/src/shared
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - NODE_PATH=/usr/src/shared
    volumes:
      - ./client:/usr/src/app
      - ./shared:/usr/src/shared
      - /usr/src/app/node_modules
    depends_on:
      - server
