name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: client
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run linter
        run: npm run lint
        working-directory: client
      - name: Run tests with coverage
        run: npm test -- --coverage
        working-directory: client
      - name: Build project
        run: npm run build
        working-directory: client
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist
          retention-days: 1

  server-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: server
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run linter
        run: npm run lint
        working-directory: server
      - name: Run tests with coverage
        run: npm test -- --coverage
        working-directory: server
      - name: Build project
        run: npm run build:ui
        working-directory: server
        env:
          PROJECT_DIR: ${{ github.workspace }}
